//
// prometheus.proto
//

//---------------------------------------------------
//
// This protobuf allows collecting of data from go programs that
// have prometheus counters and histrograms described
//
// Please note the key idea is to constrain the label entropy, so
// we have exactly x3 labels per metric
//
// The go programs have the promethus counters implmented like this:

// startTime := time.Now()
// defer func() {
//   d.pH.WithLabelValues("Deserialize", "complete", "count").Observe(time.Since(startTime).Seconds())
// }()
// d.pC.WithLabelValues("Deserialize", "start", "count").Inc()

// Error counters
// d.pC.WithLabelValues("Deserialize", "netlinkerDoneCh", "error").Inc()

// x.pC = promauto.NewCounterVec(
//   prometheus.CounterOpts{
//     Subsystem: "xtcp",
//     Name:      "counts",
//     Help:      "xtcp counts",
//   },
//   []string{"function", "variable", "type"},
// )

// x.pH = promauto.NewSummaryVec(
//   prometheus.SummaryOpts{
//     Subsystem: "xtcp",
//     Name:      "histograms",
//     Help:      "xtcp historgrams",
//     Objectives: map[float64]float64{
//       0.1:  quantileError,
//       0.5:  quantileError,
//       0.99: quantileError,
//     },
//     MaxAge: summaryVecMaxAge,
//   },
//   []string{"function", "variable", "type"},
// )
//---------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: prometheus/v1/prometheus.proto

package prometheus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromRecordCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   float64                `protobuf:"fixed64,10,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Hostname      string                 `protobuf:"bytes,20,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pop           string                 `protobuf:"bytes,30,opt,name=pop,proto3" json:"pop,omitempty"`
	Label         string                 `protobuf:"bytes,50,opt,name=label,proto3" json:"label,omitempty"` // free form string
	Tag           string                 `protobuf:"bytes,60,opt,name=tag,proto3" json:"tag,omitempty"`     // free form string
	RecordCounter uint64                 `protobuf:"varint,70,opt,name=record_counter,json=recordCounter,proto3" json:"record_counter,omitempty"`
	Function      string                 `protobuf:"bytes,80,opt,name=function,proto3" json:"function,omitempty"` // []string{"function", "variable", "type"},
	Variable      string                 `protobuf:"bytes,90,opt,name=variable,proto3" json:"variable,omitempty"`
	Type          string                 `protobuf:"bytes,100,opt,name=type,proto3" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,110,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromRecordCounter) Reset() {
	*x = PromRecordCounter{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromRecordCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromRecordCounter) ProtoMessage() {}

func (x *PromRecordCounter) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromRecordCounter.ProtoReflect.Descriptor instead.
func (*PromRecordCounter) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{0}
}

func (x *PromRecordCounter) GetTimestampNs() float64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *PromRecordCounter) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PromRecordCounter) GetPop() string {
	if x != nil {
		return x.Pop
	}
	return ""
}

func (x *PromRecordCounter) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PromRecordCounter) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PromRecordCounter) GetRecordCounter() uint64 {
	if x != nil {
		return x.RecordCounter
	}
	return 0
}

func (x *PromRecordCounter) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *PromRecordCounter) GetVariable() string {
	if x != nil {
		return x.Variable
	}
	return ""
}

func (x *PromRecordCounter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PromRecordCounter) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_prometheus_v1_prometheus_proto protoreflect.FileDescriptor

const file_prometheus_v1_prometheus_proto_rawDesc = "" +
	"\n" +
	"\x1eprometheus/v1/prometheus.proto\x12\rprometheus.v1\"\x95\x02\n" +
	"\x11PromRecordCounter\x12!\n" +
	"\ftimestamp_ns\x18\n" +
	" \x01(\x01R\vtimestampNs\x12\x1a\n" +
	"\bhostname\x18\x14 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pop\x18\x1e \x01(\tR\x03pop\x12\x14\n" +
	"\x05label\x182 \x01(\tR\x05label\x12\x10\n" +
	"\x03tag\x18< \x01(\tR\x03tag\x12%\n" +
	"\x0erecord_counter\x18F \x01(\x04R\rrecordCounter\x12\x1a\n" +
	"\bfunction\x18P \x01(\tR\bfunction\x12\x1a\n" +
	"\bvariable\x18Z \x01(\tR\bvariable\x12\x12\n" +
	"\x04type\x18d \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18n \x01(\x01R\x05valueB\x8b\x01\n" +
	"\x11com.prometheus.v1B\x0fPrometheusProtoP\x01Z\x10./pkg/prometheus\xa2\x02\x03PXX\xaa\x02\rPrometheus.V1\xca\x02\rPrometheus\\V1\xe2\x02\x19Prometheus\\V1\\GPBMetadata\xea\x02\x0ePrometheus::V1b\x06proto3"

var (
	file_prometheus_v1_prometheus_proto_rawDescOnce sync.Once
	file_prometheus_v1_prometheus_proto_rawDescData []byte
)

func file_prometheus_v1_prometheus_proto_rawDescGZIP() []byte {
	file_prometheus_v1_prometheus_proto_rawDescOnce.Do(func() {
		file_prometheus_v1_prometheus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prometheus_v1_prometheus_proto_rawDesc), len(file_prometheus_v1_prometheus_proto_rawDesc)))
	})
	return file_prometheus_v1_prometheus_proto_rawDescData
}

var file_prometheus_v1_prometheus_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_prometheus_v1_prometheus_proto_goTypes = []any{
	(*PromRecordCounter)(nil), // 0: prometheus.v1.PromRecordCounter
}
var file_prometheus_v1_prometheus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prometheus_v1_prometheus_proto_init() }
func file_prometheus_v1_prometheus_proto_init() {
	if File_prometheus_v1_prometheus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prometheus_v1_prometheus_proto_rawDesc), len(file_prometheus_v1_prometheus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prometheus_v1_prometheus_proto_goTypes,
		DependencyIndexes: file_prometheus_v1_prometheus_proto_depIdxs,
		MessageInfos:      file_prometheus_v1_prometheus_proto_msgTypes,
	}.Build()
	File_prometheus_v1_prometheus_proto = out.File
	file_prometheus_v1_prometheus_proto_goTypes = nil
	file_prometheus_v1_prometheus_proto_depIdxs = nil
}
